const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: 44,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 80,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-1',
      name: 'Gracewood Hollow Driftwood 1',
      category: 'chair',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MGGzLRTJ/gracewood-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-2',
      name: 'Gracewood Hollow Driftwood 2',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-3',
      name: 'Gracewood Hollow Driftwood 3',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/NM3YLzxQ/gracewood-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-4',
      name: 'Gracewood Hollow Driftwood 4',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/tTZpqjWr/gracewood-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-5',
      name: 'Gracewood Hollow Driftwood 5',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-6',
      name: 'Gracewood Hollow Driftwood 6',
      category: 'chair',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MH1wBmsV/gracewood-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-7',
      name: 'Gracewood Hollow Driftwood 7',
      category: 'chair',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MGGzLRTJ/gracewood-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-8',
      name: 'Gracewood Hollow Driftwood 8',
      category: 'chair',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MH1wBmsV/gracewood-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-9',
      name: 'Gracewood Hollow Driftwood 9',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-10',
      name: 'Gracewood Hollow Driftwood 10',
      category: 'chair',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MGGzLRTJ/gracewood-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-11',
      name: 'Gracewood Hollow Driftwood 11',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/tTZpqjWr/gracewood-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-132',
      name: 'Gracewood Hollow Driftwood 132',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-13',
      name: 'Gracewood Hollow Driftwood 13',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/tTZpqjWr/gracewood-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-14',
      name: 'Gracewood Hollow Driftwood 14',
      category: 'chair',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MGGzLRTJ/gracewood-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-15',
      name: 'Gracewood Hollow Driftwood 15',
      category: 'chair',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MGGzLRTJ/gracewood-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-16',
      name: 'Gracewood Hollow Driftwood 16',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-17',
      name: 'Gracewood Hollow Driftwood 17',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/NM3YLzxQ/gracewood-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-18',
      name: 'Gracewood Hollow Driftwood 18',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/tTZpqjWr/gracewood-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-19',
      name: 'Gracewood Hollow Driftwood 19',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-20',
      name: 'Gracewood Hollow Driftwood 20',
      category: 'chair',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MH1wBmsV/gracewood-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-21',
      name: 'Gracewood Hollow Driftwood 21',
      category: 'chair',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MH1wBmsV/gracewood-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-22',
      name: 'Gracewood Hollow Driftwood 22',
      category: 'chair',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MH1wBmsV/gracewood-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-23',
      name: 'Gracewood Hollow Driftwood 23',
      category: 'chair',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/VNHzP6rr/gracewood-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-24',
      name: 'Gracewood Hollow Driftwood 24',
      category: 'chair',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/MGGzLRTJ/gracewood-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'gracewood-hollow-driftwood-25',
      name: 'Gracewood Hollow Driftwood 25',
      category: 'chair',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/tTZpqjWr/gracewood-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-1',
      name: 'Cooper Grove Harzburg 1',
      category: 'sofa',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cC338Pyh/cooper-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-2',
      name: 'Cooper Grove Harzburg 2',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-3',
      name: 'Cooper Grove Harzburg 3',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/htcmfCC8/cooper-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-4',
      name: 'Cooper Grove Harzburg 4',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/WbRgPpgH/cooper-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-5',
      name: 'Cooper Grove Harzburg 5',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-6',
      name: 'Cooper Grove Harzburg 6',
      category: 'sofa',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/GhkY30jh/cooper-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-7',
      name: 'Cooper Grove Harzburg 7',
      category: 'sofa',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cC338Pyh/cooper-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-8',
      name: 'Cooper Grove Harzburg 8',
      category: 'sofa',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/GhkY30jh/cooper-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-9',
      name: 'Cooper Grove Harzburg 9',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-10',
      name: 'Cooper Grove Harzburg 10',
      category: 'sofa',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cC338Pyh/cooper-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-11',
      name: 'Cooper Grove Harzburg 11',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/WbRgPpgH/cooper-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-132',
      name: 'Cooper Grove Harzburg 132',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-13',
      name: 'Cooper Grove Harzburg 13',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/WbRgPpgH/cooper-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-14',
      name: 'Cooper Grove Harzburg 14',
      category: 'sofa',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cC338Pyh/cooper-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-15',
      name: 'Cooper Grove Harzburg 15',
      category: 'sofa',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cC338Pyh/cooper-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-16',
      name: 'Cooper Grove Harzburg 16',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-17',
      name: 'Cooper Grove Harzburg 17',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/htcmfCC8/cooper-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-18',
      name: 'Cooper Grove Harzburg 18',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/WbRgPpgH/cooper-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-19',
      name: 'Cooper Grove Harzburg 19',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-20',
      name: 'Cooper Grove Harzburg 20',
      category: 'sofa',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/GhkY30jh/cooper-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-21',
      name: 'Cooper Grove Harzburg 21',
      category: 'sofa',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/GhkY30jh/cooper-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-22',
      name: 'Cooper Grove Harzburg 22',
      category: 'sofa',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/GhkY30jh/cooper-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-23',
      name: 'Cooper Grove Harzburg 23',
      category: 'sofa',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/nV9B59jm/cooper-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-24',
      name: 'Cooper Grove Harzburg 24',
      category: 'sofa',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cC338Pyh/cooper-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'cooper-grove-harzburg-25',
      name: 'Cooper Grove Harzburg 25',
      category: 'sofa',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/WbRgPpgH/cooper-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-1',
      name: 'Carson Carrington Cranesbill 1',
      category: 'table',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-2',
      name: 'Carson Carrington Cranesbill 2',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-3',
      name: 'Carson Carrington Cranesbill 3',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-4',
      name: 'Carson Carrington Cranesbill 4',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-5',
      name: 'Carson Carrington Cranesbill 5',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-6',
      name: 'Carson Carrington Cranesbill 6',
      category: 'table',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-7',
      name: 'Carson Carrington Cranesbill 7',
      category: 'table',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-8',
      name: 'Carson Carrington Cranesbill 8',
      category: 'table',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-9',
      name: 'Carson Carrington Cranesbill 9',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-10',
      name: 'Carson Carrington Cranesbill 10',
      category: 'table',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-11',
      name: 'Carson Carrington Cranesbill 11',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-132',
      name: 'Carson Carrington Cranesbill 132',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-13',
      name: 'Carson Carrington Cranesbill 13',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-14',
      name: 'Carson Carrington Cranesbill 14',
      category: 'table',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-15',
      name: 'Carson Carrington Cranesbill 15',
      category: 'table',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-16',
      name: 'Carson Carrington Cranesbill 16',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-17',
      name: 'Carson Carrington Cranesbill 17',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-18',
      name: 'Carson Carrington Cranesbill 18',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-19',
      name: 'Carson Carrington Cranesbill 19',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-20',
      name: 'Carson Carrington Cranesbill 20',
      category: 'table',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-21',
      name: 'Carson Carrington Cranesbill 21',
      category: 'table',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-22',
      name: 'Carson Carrington Cranesbill 22',
      category: 'table',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/cJZNq3LL/carson-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-23',
      name: 'Carson Carrington Cranesbill 23',
      category: 'table',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/vZ5dShMK/carson-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-24',
      name: 'Carson Carrington Cranesbill 24',
      category: 'table',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'carson-carrington-cranesbill-25',
      name: 'Carson Carrington Cranesbill 25',
      category: 'table',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/Dy9TgHVs/carson-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-1',
      name: 'Villa Bellcrest Skyline 1',
      category: 'dining',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/fy6RYbjS/villa-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-2',
      name: 'Villa Bellcrest Skyline 2',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-3',
      name: 'Villa Bellcrest Skyline 3',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/J4knMbMN/villa-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-4',
      name: 'Villa Bellcrest Skyline 4',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-5',
      name: 'Villa Bellcrest Skyline 5',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-6',
      name: 'Villa Bellcrest Skyline 6',
      category: 'dining',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/J4knMbMN/villa-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-7',
      name: 'Villa Bellcrest Skyline 7',
      category: 'dining',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-8',
      name: 'Villa Bellcrest Skyline 8',
      category: 'dining',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/J4knMbMN/villa-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-9',
      name: 'Villa Bellcrest Skyline 9',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-10',
      name: 'Villa Bellcrest Skyline 10',
      category: 'dining',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/fy6RYbjS/villa-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-11',
      name: 'Villa Bellcrest Skyline 11',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-132',
      name: 'Villa Bellcrest Skyline 132',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-13',
      name: 'Villa Bellcrest Skyline 13',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/fy6RYbjS/villa-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-14',
      name: 'Villa Bellcrest Skyline 14',
      category: 'dining',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/fy6RYbjS/villa-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-15',
      name: 'Villa Bellcrest Skyline 15',
      category: 'dining',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-16',
      name: 'Villa Bellcrest Skyline 16',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-17',
      name: 'Villa Bellcrest Skyline 17',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/J4knMbMN/villa-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-18',
      name: 'Villa Bellcrest Skyline 18',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-19',
      name: 'Villa Bellcrest Skyline 19',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-20',
      name: 'Villa Bellcrest Skyline 20',
      category: 'dining',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/J4knMbMN/villa-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-21',
      name: 'Villa Bellcrest Skyline 21',
      category: 'dining',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-22',
      name: 'Villa Bellcrest Skyline 22',
      category: 'dining',
      price: 40,
      oldPrice: 60,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/J4knMbMN/villa-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-23',
      name: 'Villa Bellcrest Skyline 23',
      category: 'dining',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/mZqDvdfZ/villa-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-24',
      name: 'Villa Bellcrest Skyline 24',
      category: 'dining',
      price: 40,
      oldPrice: 55,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/3xQwRdxP/villa-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'villa-bellcrest-skyline-25',
      name: 'Villa Bellcrest Skyline 25',
      category: 'dining',
      price: 40,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/fy6RYbjS/villa-1.jpg',
      wishlist: false,
      compare: false,
    },
  ],
  cart: {
    products: [],
  },
};

export default initialState;
