const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: 44,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 80,
      stars: 2,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: false,
      compare: false,
      hotDeal: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 5,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: 120,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: false,
      compare: false,
      hotDeal: true,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      userStars: 4,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: false,
      compare: false,
      hotDeal: true,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/G2W07cfW/bristique-5.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/02qR7yDm/bristique-1.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/YqfcRBzP/bristique-2.jpg',
      wishlist: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/HWM1Jycd/bristique-3.jpg',
      wishlist: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      img: 'https://i.postimg.cc/sx7kbkdv/bristique-4.jpg',
      wishlist: false,
      compare: false,
    },
  ],
  cart: {
    products: [],
  },
  device: '',
  banner: [
    {
      id: 0,
      url:
        'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      alt: 'furniture',
    },
    {
      id: 1,
      url:
        'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
      alt: 'bed',
    },
    {
      id: 2,
      url:
        'https://images.pexels.com/photos/1139784/pexels-photo-1139784.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
      alt: 'bedroom',
    },
  ],
  feedbacks: [
    {
      name: 'Zibi Boniek',
      image: 'https://dimg.wprost.pl/_thumb/d0/4b/e9ff336fd1b1ee5b288f0c3096f8.jpeg',
      status: 'Future client',
      opinion:
        'Rejent był maleńki ogródek, ścieżkami porznięty pełen bukietów trawy angielskiej i przepraszał Sędziego. Sędzia nigdy sługom należy chartu Sokołowi. ',
    },
    {
      name: 'Fernando Alonso',
      image:
        'https://bi.im-g.pl/im/3a/16/17/z24210234AMP,Fernando-Alonso--Czy-Fernando-Alonso-wroci-do-Form.jpg',
      status: 'Racer',
      opinion:
        'Lorem ipsum dolor sit amet, his ancillae signiferumque in, vel inermis vituperatoribus eu. An cum quando detracto, at intellegebat conclusionemque pro, usu illum erant mentitum no. In posse porro cum, eam saepe veniam delicatissimi ne, ei vidisse menandri repudiare eam. Inani delicata an eam. ',
    },
    {
      name: 'Lukas Podolski',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/2/20/2016209185709_2016-07-27_Champions_for_Charity_-_Sven_-_1D_X_-_0125_-_DV3P4718_mod.jpg',
      status: 'Future client',
      opinion:
        'Deutsches Ipsum Dolor quo lucilius Kreuzberg at, adhuc laboramus sadipscing per Brezel in mei ullum gloriatur. Id Käsefondue recteque accommodare sed. Id nec Goethe argumentum, te melius erroribus vix. Faust ut amet causae iriure, prodesset Bratwurst mea ut. Dicunt virtute suscipit Nackenheim no. At nemore scaevola eum. Anwendungsprogrammierschnittstelle regione malorum efficiendi ius',
    },
  ],
};

export default initialState;
